# docker-compose.yml

version: "3.8"
# services
services:
  wetty:
    image: "wuchujie/wetty:latest"
    build:
      context: .
      dockerfile: containers/wetty/Dockerfile
    tty: true
    working_dir: /usr/src/app

  neovim-server:
    image: "wuchujie/nvim-server:latest"
    depends_on:
      - wetty
    build:
      context: .
      dockerfile: containers/nvim-server/Dockerfile
    tty: true
    # working_dir: /workspace
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - USER=guest
      - SECRET=passwd
      - TZ=Asia/Shanghai
    volumes:
      - $HOME/workspace:/workspace # workspace
      - $HOME/.config/cosynvim/:/config # nvim config
    restart: unless-stopped
